name: amgp
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytest
  - python >= 3.9
  - scikit-learn
  - scipy
prefix: /Users/olivne/.conda/envs/amgp
